package cse3461;

import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Stroke;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Vector;

import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 
 * @author Sunny
 */
public class a2 extends javax.swing.JFrame implements MouseListener,
		MouseMotionListener {

	private Point[] stroke;
	private int sampleCount = 0;

	/**
	 * Creates new form a2
	 */
	public a2() {
		initComponents();
		groupButton();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		sampleCount = 0;
		stroke = new Point[MAX_SAMPLES];

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jPanel1 = new javax.swing.JPanel();
		Eraser1 = new javax.swing.JRadioButton();
		Brush = new javax.swing.JRadioButton();
		Line1 = new javax.swing.JRadioButton();
		Pencil = new javax.swing.JRadioButton();
		Text = new javax.swing.JButton();
		ColorBtn = new javax.swing.JButton();
		jMenuBar2 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		Open = new javax.swing.JMenuItem();
		Save = new javax.swing.JMenuItem();
		Quit = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		Color = new javax.swing.JMenuItem();
		Rectangle = new javax.swing.JRadioButton();
		Circle = new javax.swing.JRadioButton();
		clearButton = new javax.swing.JButton();
		clearImage = new javax.swing.JButton();
		rotateImage = new javax.swing.JButton();
		// radian = 0.0f;

		jMenu1.setText("File");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);

		jMenuItem1.setText("jMenuItem1");

		inkPanel = new PaintPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		final JPanel contentPane = new JPanel(new BorderLayout());

		inkPanel.addMouseListener(this);
		inkPanel.addMouseMotionListener(this);
		jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(
				0, 0, 0), 1, true));

		Eraser1.setText("Eraser");
		Eraser1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// Eraser1ActionPerformed(evt);
			}
		});

		Rectangle.setText("Rectangle");
		Circle.setText("Circle");

		final JPanel p1 = new JPanel(new BorderLayout());
		p1.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
		p1.add(inkPanel, "Center");

		Brush.setText("Brush");
		Brush.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// BrushActionPerformed(evt);
			}
		});

		Line1.setText("Line");
		Line1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// Line1ActionPerformed(evt);
			}
		});

		Pencil.setText("Pencil");
		Pencil.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// PencilActionPerformed(evt);
			}
		});

		Text.setText("Stroke++");
		Text.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				i++;
				INK_STROKE = new BasicStroke((float) 5.0 + i,
						BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND);
				;
			}
		});

		clearButton = new JButton("Clear");
		clearButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				inkPanel.clear();
				// contentPane.remove(pp);
				// contentPane.add(p1);
				sampleCount = 0;
				// repaint();
			}
		});

		/**
		 * Can be used to clear images as well. Very useful feature.
		 */
		clearImage = new JButton("Clear Image");
		clearImage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (pp != null) {
					inkPanel.clear();
					contentPane.remove(pp);
					contentPane.add(p1);
					sampleCount = 0;
					repaint();
				}
			}
		});

		rotateImage = new JButton("Rotate Image");
		rotateImage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (pp != null) {
					int width = pp.getWidth();
					int height = pp.getHeight();
					
					BufferedImage bi = (BufferedImage) createImage(width, height);
					Graphics2D g2d = (Graphics2D) bi.createGraphics();
					radian = (float) Math.PI / 2; // angle
					g2d.translate(width / 2, height / 2);
					g2d.rotate(radian); // rotate the image
					g2d.translate(-width / 2, -height / 2);
					g2d.drawImage(img, 0, 0, null); // draw the rotated image
					img = bi;
					g2d.dispose();
					
					//width = pp.getWidth();
					//height = pp.getHeight();
					
					contentPane.remove(pp);
					pp = new PaintPanel2(img);

					pp.setPreferredSize(new Dimension (width, height));
					// contentPane.remove(p1);
					contentPane.add(pp);
					pack();
				}
			}
		});

		ColorBtn.setText("Color");
		ColorBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ColorBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(Brush).addComponent(Line1).addComponent(Pencil)
				.addComponent(Eraser1).addComponent(Text).addComponent(Circle)
				.addComponent(Rectangle).addComponent(ColorBtn)
				.addComponent(clearImage).addComponent(clearButton)
				.addComponent(rotateImage));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(Line1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(Rectangle)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(Brush)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(Circle)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(Pencil)
										.addGap(12, 12, 12)
										.addComponent(Eraser1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(ColorBtn)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(clearButton)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(Text)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(clearImage)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(rotateImage)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)));

		jMenu3.setMnemonic('F');
		jMenu3.setText("File");

		Quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_Q,
				java.awt.event.InputEvent.CTRL_MASK));
		Quit.setMnemonic('Q');
		Quit.setText("Quit");
		Quit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				System.exit(0);
			}
		});

		Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_O,
				java.awt.event.InputEvent.CTRL_MASK));
		Open.setMnemonic('O');
		Open.setText("Open");
		Open.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				final JFileChooser fc = new JFileChooser();
				int returnVal = fc.showOpenDialog(a2.this);
				if (returnVal == JFileChooser.APPROVE_OPTION) {
					File file = fc.getSelectedFile();
					FileNameExtensionFilter filter = new FileNameExtensionFilter(
							"png", "jpg", "gif");
					// This is where a real application would open the file.
					fc.setFileFilter(filter);

					try {
						img = ImageIO.read(file);
						pp = new PaintPanel2(img);
						// pp.setBounds(100, 40, 500, 400);
						pp.setPreferredSize(new Dimension(img.getWidth(), img
								.getHeight()));
						// System.out.println("SUCCESS");
						contentPane.remove(p1);
						contentPane.add(pp);
						pack();

					} catch (IOException e) {
						System.out.println("Invalid File Format.");
					} catch (NullPointerException e) {
						System.out.println("Invalid File Format.");
					}

				} else {
					// JOptionPane.showMessageDialog(contentPane,
					// "Can't Open File. Try Again.");
				}
			}
		});
		jMenu3.add(Open);

		Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_S,
				java.awt.event.InputEvent.CTRL_MASK));
		Save.setMnemonic('S');
		Save.setText("Save");
		Save.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SaveActionPerformed(evt);
			}
		});
		jMenu3.add(Save);
		jMenu3.add(Quit);

		jMenuBar2.add(jMenu3);

		jMenu4.setText("Edit");
		jMenu4.setMnemonic('E');

		Color.setText("Choose Color");
		Color.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				INK_COLOR = JColorChooser.showDialog(null, "Choose a Color",
						new Color(0, 0, 0));
			}
		});
		jMenu4.add(Color);

		jMenuBar2.add(jMenu4);

		setJMenuBar(jMenuBar2);

		p1.setPreferredSize(new Dimension(800, 600));
		p1.setMaximumSize(new Dimension(2000, 1600));

		contentPane.add(p1, BorderLayout.CENTER);
		contentPane.add(jPanel1, BorderLayout.WEST);

		this.setContentPane(contentPane);
		pack();
	}// </editor-fold>

	private void SaveActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void ColorBtnActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Color c = JColorChooser.showDialog(null, "Choose a Color",
					new Color(0, 0, 0));
			INK_COLOR = c;
		} catch (IllegalArgumentException ex) {
			JOptionPane.showMessageDialog(null, "Choose Wisely.");
		}
	}

	private void groupButton() {
		ButtonGroup bg1 = new ButtonGroup();
		bg1.add(Brush);
		bg1.add(Pencil);
		bg1.add(Eraser1);
		bg1.add(Line1);
		bg1.add(Circle);
		bg1.add(Rectangle);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(a2.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(a2.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(a2.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(a2.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new a2().setVisible(true);
			}
		});
	}

	private javax.swing.JFileChooser fc;
	private javax.swing.JRadioButton Brush;
	private javax.swing.JMenuItem Color;
	private javax.swing.JButton ColorBtn;
	private javax.swing.JRadioButton Eraser1;
	private javax.swing.JRadioButton Line1;
	private javax.swing.JMenuItem Open;
	private javax.swing.JMenuItem Quit;
	private javax.swing.JRadioButton Pencil;
	private javax.swing.JRadioButton Rectangle;
	private javax.swing.JRadioButton Circle;
	private javax.swing.JMenuItem Save;
	private PaintPanel inkPanel;
	private javax.swing.JButton Text;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton clearButton;
	private javax.swing.JButton clearImage;
	private javax.swing.JButton rotateImage;
	final int MAX_SAMPLES = 500000;
	PaintPanel2 pp = null;
	private Color INK_COLOR = null;
	private Stroke INK_STROKE = null;
	private float i = 0.0f;
	private float radian = 0.0f;
	BufferedImage img = null;

	// End of variables declaration
	@Override
	public void mouseDragged(MouseEvent me) {
		if (Pencil.isSelected()) {
			int x = me.getX();
			int y = me.getY();

			stroke[sampleCount] = new Point(x, y);

			if (SwingUtilities.isLeftMouseButton(me)) {
				stroke[sampleCount] = new Point(x, y);
				int x1 = (int) stroke[sampleCount - 1].getX();
				int y1 = (int) stroke[sampleCount - 1].getY();
				int x2 = (int) stroke[sampleCount].getX();
				int y2 = (int) stroke[sampleCount].getY();
				sampleCount++;

				// draw ink trail from previous point to current point
				inkPanel.drawInk(x1, y1, x2, y2);
			}

		} else if (Brush.isSelected()) {
			int x = me.getX();
			int y = me.getY();

			stroke[sampleCount] = new Point(x, y);

			if (SwingUtilities.isLeftMouseButton(me)) {
				stroke[sampleCount] = new Point(x, y);
				int x1 = (int) stroke[sampleCount - 1].getX();
				int y1 = (int) stroke[sampleCount - 1].getY();
				int x2 = (int) stroke[sampleCount].getX();
				int y2 = (int) stroke[sampleCount].getY();
				sampleCount++;

				// draw ink trail from previous point to current point
				inkPanel.drawInk2(x1, y1, x2, y2);
			}
		} else if (Line1.isSelected()) {

		} else if (Eraser1.isSelected()) {
			int x = me.getX();
			int y = me.getY();

			stroke[sampleCount] = new Point(x, y);

			if (SwingUtilities.isLeftMouseButton(me)) {
				stroke[sampleCount] = new Point(x, y);
				int x1 = (int) stroke[sampleCount - 1].getX();
				int y1 = (int) stroke[sampleCount - 1].getY();
				int x2 = (int) stroke[sampleCount].getX();
				int y2 = (int) stroke[sampleCount].getY();
				sampleCount++;

				// draw ink trail from previous point to current point
				inkPanel.drawInk3(x1, y1, x2, y2);
			}
		} else if (Text.isSelected()) {

		} else {
			;
		}
	}

	@Override
	public void mouseMoved(MouseEvent me) {
		// TODO Auto-generated method stub
	}

	@Override
	public void mouseClicked(MouseEvent me) {
		int x = me.getX();
		int y = me.getY();

		if (Circle.isSelected())
			inkPanel.drawCircle(x, y);
		if (Rectangle.isSelected())
			inkPanel.drawRectangle(x, y);
	}

	@Override
	public void mouseEntered(MouseEvent e) {
	}

	@Override
	public void mouseExited(MouseEvent e) {
	}

	@Override
	public void mousePressed(MouseEvent me) {
		// TODO Auto-generated method stub
		if (Pencil.isSelected()) {
			int x = me.getX();
			int y = me.getY();

			stroke[sampleCount] = new Point(x, y);
			sampleCount++;

		} else if (Brush.isSelected()) {
			int x = me.getX();
			int y = me.getY();

			stroke[sampleCount] = new Point(x, y);
			sampleCount++;

		} else if (Line1.isSelected()) {
			int x = me.getX();
			int y = me.getY();

			stroke[sampleCount] = new Point(x, y);
			sampleCount++;

			inkPanel.drawInk(x, y);

		} else if (Eraser1.isSelected()) {
			int x = me.getX();
			int y = me.getY();

			stroke[sampleCount] = new Point(x, y);
			sampleCount++;
		} else if (Text.isSelected()) {

		} else {
			;
		}
	}

	@Override
	public void mouseReleased(MouseEvent me) {
		// TODO Auto-generated method stub
		if (Line1.isSelected()) {

			int x1 = (int) stroke[sampleCount - 1].getX();
			int y1 = (int) stroke[sampleCount - 1].getY();
			int x2 = (int) me.getX();
			int y2 = (int) me.getY();
			// System.out.printf("%d,  %d, %d, %d", x1, y1, x2, y2);

			// draw ink trail from previous point to current point
			inkPanel.drawInk(x1, y1, x2, y2);
		}

		if (SwingUtilities.isLeftMouseButton(me)) {
			sampleCount = 0;
		}
	}

	private class WindowCloser extends WindowAdapter {
		// the following avoids a "warning" with Java 1.5.0 complier (?)
		static final long serialVersionUID = 42L;

		public void windowClosing(WindowEvent event) {
			System.exit(0);
		}
	}

	/**
	 * FOR TA:
	 * 
	 * The below class is used as replacement for Canvas class to draw our
	 * lines/ shapes. I realize that this class has many limitations. I have
	 * tried to implement it correctly but the following issues still exist: 1)
	 * if I have drawn a line, and then drawn a brush, when repainting it paints
	 * both line and brush with the same colour (may have been drawn using
	 * different colours) and same size (diferent strokes are used, but repaint
	 * method paintInkStroke(Graphics g) doesn't realize this. 2) it doesn't
	 * repaint circles and rectangle due after window size change because both
	 * these shapes are not used in paintInkStroke(Graphics g) method. 3)
	 * Initially, I wanted to load an image, and draw each pixel onto
	 * PaintPanel's inkPanel variable; however, this was impossible with my
	 * limited knowledge. Hence, whenever I open an image, it loads and is
	 * displayed on screen. But we cannot edit/ save the image as it's just
	 * BufferedImage and not belong to a canvas or PaintPanel class.
	 */

	class PaintPanel extends JPanel {
		// the following avoids a "warning" with Java 1.5.0 complier (?)
		static final long serialVersionUID = 42L;

		private Vector<Line2D.Double> v;

		PaintPanel() {
			INK_COLOR = new Color(0, 0, 0);
			INK_STROKE = new BasicStroke(5.0f, BasicStroke.CAP_ROUND,
					BasicStroke.JOIN_ROUND);
			Color c = new Color(255, 255, 255);
			v = new Vector<Line2D.Double>();
			this.setBackground(c);
		}

		public void paintComponent(Graphics g) {
			super.paintComponent(g);
			paintInkStrokes(g);
		}

		/**
		 * Paint all the line segments stored in the vector
		 */
		private void paintInkStrokes(Graphics g) {
			Graphics2D graph2D = (Graphics2D) g;

			// set the inking color
			graph2D.setColor(INK_COLOR);

			// set the stroke thickness, and cap and join attributes ('round')
			Stroke s = graph2D.getStroke(); // save current stroke

			if (Brush.isSelected()) {
				Stroke INK_STROKE3 = new BasicStroke((float) 15.0 + i,
						BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND);
				graph2D.setStroke(INK_STROKE3);
			} else {
				graph2D.setStroke(INK_STROKE);
			}

			// retrive each line segment and draw it
			for (int i = 0; i < v.size(); ++i)
				graph2D.draw((Line2D.Double) v.elementAt(i));

			graph2D.setStroke(s); // restore stroke
		}

		/**
		 * Draw one line segment, then add it to the vector.
		 * <p>
		 */
		public void drawInk(int x1, int y1, int x2, int y2) {
			// get graphics context
			Graphics2D graph2D = (Graphics2D) this.getGraphics();

			// create the line
			Line2D.Double inkSegment = new Line2D.Double(x1, y1, x2, y2);

			graph2D.setColor(INK_COLOR);
			Stroke s = graph2D.getStroke();
			graph2D.setStroke(INK_STROKE);
			graph2D.draw(inkSegment); // draw it!
			graph2D.setStroke(s);
			v.add(inkSegment); // add to vector
		}

		public void drawInk(int x1, int y1) {
			Graphics2D graph2D = (Graphics2D) this.getGraphics();

			Line2D.Double inkSegment = new Line2D.Double(x1, y1, x1, y1);

			graph2D.setColor(INK_COLOR);
			Stroke s = graph2D.getStroke();
			Stroke INK_STROKE2 = new BasicStroke(5f, BasicStroke.CAP_SQUARE,
					BasicStroke.CAP_SQUARE);
			graph2D.setStroke(INK_STROKE2);
			graph2D.draw(inkSegment); // draw it!
			graph2D.setStroke(s);
			v.add(inkSegment); // add to vector
		}

		public void drawInk2(int x1, int y1, int x2, int y2) {
			Graphics2D graph2D = (Graphics2D) this.getGraphics();

			// create the line
			Line2D.Double inkSegment = new Line2D.Double(x1, y1, x2, y2);

			graph2D.setColor(INK_COLOR);
			Stroke s = graph2D.getStroke();
			Stroke INK_STROKE2 = new BasicStroke(15f, BasicStroke.CAP_ROUND,
					BasicStroke.JOIN_ROUND);
			graph2D.setStroke(INK_STROKE2);
			graph2D.draw(inkSegment);
			graph2D.setStroke(s);
			v.add(inkSegment);
		}

		public void drawCircle(int x, int y) {
			Graphics2D graph2D = (Graphics2D) this.getGraphics();
			graph2D.setColor(INK_COLOR);
			Ellipse2D.Double e = new Ellipse2D.Double(x, y, 25, 25);
			graph2D.draw(e);
		}

		public void drawRectangle(int x, int y) {
			Graphics2D graph2D = (Graphics2D) this.getGraphics();
			graph2D.setColor(INK_COLOR);
			Rectangle2D.Double e = new Rectangle2D.Double(x, y, 40, 25);
			graph2D.draw(e);
		}

		public void drawInk3(int x1, int y1, int x2, int y2) {
			// get graphics context
			Graphics2D graph2D = (Graphics2D) this.getGraphics();

			Line2D.Double inkSegment = new Line2D.Double(x1, y1, x2, y2);

			graph2D.setColor(inkPanel.getBackground());
			Stroke s = graph2D.getStroke(); // save current stroke
			Stroke INK_STROKE2 = new BasicStroke(15f, BasicStroke.CAP_ROUND,
					BasicStroke.JOIN_ROUND);
			graph2D.setStroke(INK_STROKE2); // set desired stroke
			graph2D.draw(inkSegment);
			graph2D.setStroke(s);
			v.add(inkSegment);
		}

		public void clear() {
			v.clear();
			this.repaint();
		}
	}

	class PaintPanel2 extends JPanel {
		// the following avoids a "warning" with Java 1.5.0 complier (?)
		static final long serialVersionUID = 42L;

		BufferedImage image;

		public PaintPanel2(BufferedImage imageArg) {
			image = imageArg;
			Color c = new Color(0, 0, 0);
			setBackground(c);
		}

		public void paintComponent(Graphics g) {
			try {
				super.paintComponent(g); // paint background
				// g.drawImage(image, 0, 0, this); // draw image
				BufferedImage bi = (BufferedImage) createImage(
						image.getWidth(), image.getHeight());
				// create the Graphics2D object from the buffered image
				Graphics2D graph2D = (Graphics2D) bi.createGraphics();
				graph2D.drawImage(bi, 0, 0, this);
				repaint();
				graph2D.dispose();
			} catch (NullPointerException e) {
				// System.out.println("Null Pointer Exception. File must be an Image.");
			}

			if (image != null) {

				int width = (int) ((image.getWidth() * getHeight() / image
						.getHeight()));
				if (width < getWidth()) {
					int leftMove = getWidth() / 2 - width / 2;
					int rightMove = getWidth() / 2 + width / 2;
					g.drawImage(image, leftMove, 0, rightMove, getHeight(), 0,
							0, image.getWidth(), image.getHeight(), null);

				} else {
					int height = (image.getHeight() * getWidth())
							/ image.getWidth();
					int topMove = getHeight() / 2 - height / 2;
					int bottomMove = getHeight() / 2 + height / 2;
					g.drawImage(image, 0, topMove, getWidth(), bottomMove, 0,
							0, image.getWidth(), image.getHeight(), null);
				}
			}
		}
	}
}
